baseURL = "https://utgo.github.io/utahgolang.site/"
languageCode = "en-us"
title = "Utah Golang"
theme = "utgo"
publishDir = "docs"

# Social links
[[params.social]]
    name = "Meetup"
    weight = 1
    url = "https://www.meetup.com/utahgophers/"

[[params.social]]
    name = "GitHub"
    weight = 2
    url = "https://github.com/utgo/"

[[params.social]]
    name = "Twitter"
    weight = 3
    url = "https://twitter.com/UtahGolang"

[[params.social]]
    name = "Slack (#utah)"
    weight = 4
    url = "https://invite.slack.golangbridge.org"

# Menu links
[[menu.main]]
    name = "About"
    weight = 1
    url = "/about/"

[[menu.main]]
    name = "Presentations"
    weight = 2
    url  = "/presentations/"
